### ISSUE TITLE
Missing `sniffio` dependency?

### ISSUE THREAD

**Issue by dhirschfeld** [python-trio/trio-asyncio#105]
`conda-forge` is complaining:

![image](https://user-images.githubusercontent.com/881019/103971088-66c44000-51b5-11eb-9158-c80eb1a12fc1.png)

...and it does indeed seem to be a required dependency?

**Comment by pquentin** [comment]
A pull request to add sniffio to setup.py install_requires would be nice!

On the other hand, attrs is listed as a dependency in setup.py but we don't actually use it directly?
