### ISSUE TITLE
run_asyncio() kwargs?

### ISSUE THREAD

**Issue by belm0** [python-trio/trio-asyncio#28]
would it be reasonable for `run_asyncio()` to propagate kwargs so that partial() isn't needed?

**Comment by smurfix** [comment]
Trio's standard scheme is that positional arguments are for the called procedure while keyword args are for the interloper.

I could certainly teach the run_* functions to be "special", but I'd like a bit more confidence that they will never require kwargs of their own. So, I might do that for 1.0 or thereabouts, but probably not sooner.

**Comment by belm0** [comment]
that's a fair policy-- closing
