### ISSUE TITLE
Use a second thread for delegation of run_forever / run_until_complete

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio-asyncio#3]
Thanks to @njsmith for the initial concept.

```
import queue
import trio
from trio_asyncio import open_loop, run_future
import threading
from functools import partial

class HackyTestingLoop(TrioEventLoop):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__blocking_job_queue = queue.Queue()
        self.__blocking_result_queue = queue.Queue()
        self.__thread = threading.Thread(
            target=trio.run,
            args=(self.__trio_thread_main,))

    async def __trio_thread_main(self):
        async with open_loop():
            while True:
                # This *blocks*
                async_fn = self.__blocking_job_queue.get()
                if async_fn is None:
                    self.close()
                    return
                result = await trio.hazmat.Result.acapture(async_fn)
                self.__blocking_result_queue.put(result)

    def __run_in_thread(self, async_fn, *args):
        if not self.__thread.is_alive():
            self.__thread.start()
        self.__blocking_job_queue.put(partial(async_fn, *args))
        return self.__blocking_result_queue.get().unwrap()

    def run_until_complete(self, fut):
        return self.__run_in_thread(run_future, fut)

    def run_forever(self):
        # TODO: need to reset the stopped Event, because asyncio loops support
        # multiple rounds of run_forever/stop/run_forever/stop. Maybe instead
        # of wait_stopped, we want a function that resets the event AND then
        # blocks waiting for it, similar to how BaseEventloop.run_forever
        # always resets the internal _stopped flag?
        self.__run_in_thread(self.wait_stopped)

    def close(self):
        self.__blocking_job_queue.put(None)
        self.__thread.join()

    def __enter__(self):
        return self

    def __exit__(self, _, _, _):
        self.close()

```
TODO: 

* an event loop policy that returns HackyTestingLoop objects
* the thread must not create its own TrioEventLoop; instead it needs to share the one that's been created-but-not-started in the main thread. Various test cases expect that.
* Stopping the loop currently is the same as dismantling it. Thus we need to move the existing _run_loop's initialization/finalizer to code called by __aenter__/__aexit__.
* Calling `.stop()` may only terminate the whole loop if `run_forever()` is not running.
* re-entering `run_until_complete()`/`run_forever()` needs to raise an error.

**Comment by njsmith** [comment]
Heh, right, I made this a subclass and everything but then forgot we needed to actually use the same object instead of calling `open_loop`.

If the stdlib's tests are difficult/inappropriate due to fiddly version skew issues, I'd also be happy with running tests on some big projects like aiohttp. I do feel like we need *some* kind of real world compatibility testing for a project like this though :-).

(For aiohttp this might look like: setting up a Travis run that downloads the latest released sdist, applies a patch to use our loop, then runs it? A nice thing about aiohttp in particular is that their test suite is already set up so they can run it on uvloop or tokio, so they've collected the loop creation code in one place.)

**Comment by smurfix** [comment]
The changes requires to do this correctly are somewhat intrusive. So I'm experimenting with integrating the thread code into the "real" main loop.

We'll see what happens.

**Comment by smurfix** [comment]
Done:
* split the trio-asyncio loop into a synchronous (separate but lock-stepped thread, created by `asyncio.new_event_loop()`, `run_forever` etc. works) and an asynchronous (Trio task within the current thread, created by `async with trio_asyncio.open_loop():`, `run_forever` and friends are not available) version.
* Tests work, including some sketchy ones written to check sync operation.

TODO:
* Learn writing Sphinx documentation, dammit.
* Restore the modified Python 3.6.4 asyncio testsuite.
* Get it to work with Travis.
* Implement converage tests and all that.
* Run the aiohttp tests with a trio-asyncio loop.
* World domination.

**Comment by smurfix** [comment]
moved to https://github.com/python-trio/trio-asyncio/projects/1

**Comment by njsmith** [comment]
:applause:

I can throw in a skeleton for sphinx docs and CI in the next day or two; I'll generate them using cookiecutter-trio.
