### ISSUE TITLE
Support sniffio

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio-asyncio#32]
Now that sniffio is a thing, trio-asyncio should support it :-)

I think basically this means, making sure that the magic cvar is set to `"asyncio"` whenever trio-asyncio is running an asyncio callback.

**Comment by smurfix** [comment]
done @ 0.8.2

**Comment by njsmith** [comment]
@belm0 there was no PR, it was merged directly into master – that's what [this discussion](https://gitter.im/python-trio/general?at=5b81c8cd4be56c5918966905) is about :-)

**Comment by belm0** [comment]
As long as the bug # is in the commit description, github will link it as far as I'm aware (i.e. no PR needed).
