### ISSUE TITLE
trio-asyncio v0.8.0 crashes on import on py35

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio-asyncio#33]
Not sure whether py35 is intended to be supported or not, but noticed [when testing trio-asyncio and pytest-trio together](https://travis-ci.org/python-trio/pytest-trio/jobs/419092404) that current trio-asyncio seems to be crashing on import:

```
___________ ERROR collecting pytest_trio/_tests/test_trio_asyncio.py ___________
../../../../virtualenv/python3.5.2/lib/python3.5/site-packages/pytest_trio/_tests/test_trio_asyncio.py:2: in <module>
    import trio_asyncio
../../../../virtualenv/python3.5.2/lib/python3.5/site-packages/trio_asyncio/__init__.py:6: in <module>
    from .loop import *  # noqa
../../../../virtualenv/python3.5.2/lib/python3.5/site-packages/trio_asyncio/loop.py:171: in <module>
    _orig_run_get = _aio_event._get_running_loop
E   AttributeError: module 'asyncio.events' has no attribute '_get_running_loop'
```

**Comment by njsmith** [comment]
Though... the same test seems to pass on py 3.5.3: https://ci.appveyor.com/project/touilleMan/pytest-trio/build/1.0.122/job/grrwby5hbttmq507
The travis failures we saw were on 3.5.0 and 3.5.2. So maybe 3.5.3 is OK?

**Comment by smurfix** [comment]
Documented: minimum supported version is 3.5.3

**Comment by pquentin** [comment]
Thanks! Do you think this could be specified in python_requires too? https://github.com/python-trio/trio-asyncio/blob/master/setup.py#L75

**Comment by smurfix** [comment]
Thanks, I missed that. Uploaded (waiting for CI).
