### ISSUE TITLE
Detect when nested nursery and asyncio loop end up in silent jamming

### ISSUE THREAD

**Issue by touilleMan** [python-trio/trio-asyncio#34]
Considering the following code:

```python
@pytest.fixture
async def nursery2():
    async with trio.open_nursery() as nursery:
        yield nursery

@pytest.fixture
async def asyncio_loop2(nursery2):
    async with trio_asyncio.open_loop() as loop:
        yield loop

@pytest.mark.trio
async def test_wrong_fixture_teardown_order(
        nursery2, asyncio_loop2, postgresql_connection_specs
):

    async def db_runner(*, task_status=trio.TASK_STATUS_IGNORED):
        async with triopg.connect(**postgresql_connection_specs):
            task_status.started()

    await nursery2.start(db_runner)
```
Running this test will hang forever (dosn't even react to ^C)

The trouble is `asyncio_loop2` will be teardown before `nursery2` given it depends on it.
But given `nursery2` contains a coroutine that will call trio-asyncio it end up in a weird jammed state.

This issue also occurs with when nesting nursery and asyncio_loop in the wrong order, though there is less magic involve so it's much easier to realize the issue than with pytest trio-flavored fixtures:

```python
@pytest.mark.trio
async def test_wrong_context_manager_order(
        postgresql_connection_specs
):
    async def db_runner(*, task_status=trio.TASK_STATUS_IGNORED):
        async with triopg.connect(**postgresql_connection_specs):
            task_status.started()

    async with trio.open_nursery() as nursery:
        async with trio_asyncio.open_loop():
            await nursery.start(db_runner)
```

I'm wondering if we could come up with a solution to easily detect this, for instance using a context var as a canary to detect if there is no longer any trio-asyncio loop available in the current context.

**Comment by touilleMan** [comment]
> which will (I hope …) cause a huge nasty traceback instead of hanging.

That would be much better indeed ^^

Is there something I can do to help on this ?

**Comment by touilleMan** [comment]
@smurfix I've created a PR with two tests hanging forever (not sure where to put them though, so there are in `test_misc.py` for the moment...)

**Comment by smurfix** [comment]
Should be solved in https://github.com/python-trio/trio-asyncio/pull/38
