### ISSUE TITLE
Deprecation warning from trio.Queue

### ISSUE THREAD

**Issue by AdrienPensart** [python-trio/trio-asyncio#46]
Hello,

I'm using trio-asyncio and it works very well !

But I now have this warning : 

`python3.6/site-packages/trio_asyncio/base.py:153: TrioDeprecationWarning: trio.Queue is deprecated since Trio 0.9.0; use trio.open_memory_channel instead (https://github.com/python-trio/trio/issues/497)`

Is it trivial to fix ? I can try a PR maybe.

**Comment by smurfix** [comment]
Should be quite easy. Please do.
