### ISSUE TITLE
Setup dependency on pytest-runner makes installation hard in the walled environments

### ISSUE THREAD

**Issue by nonsleepr** [python-trio/trio-asyncio#47]
`setup.py` specifies `setup_requires=['pytest-runner']` which, if not present, would be installed using `EasyInstall` which wouldn't respect any pip options, like custom index URLs.
As a workaround, `pytest-runner` documentation suggests using [conditional dependency](https://github.com/pytest-dev/pytest-runner#conditional-requirement). Alternatively, that dependency could be completely eliminated (`make test` runs `pytest` anyway).

**Comment by njsmith** [comment]
I'd be fine with dropping this... `setup.py test` is a neat idea that never really took off. And all the other python-trio projects recommend calling pytest directly anyway. @smurfix I think you set this up – any opinion?

**Comment by nonsleepr** [comment]
I'd suggest switching to tox to cover different versions of python (any maybe trio too). Drafted it in #48.

**Comment by smurfix** [comment]
Merged.
