### ISSUE TITLE
TrioDeprecationWarning: trio.open_cancel_scope is deprecated since Trio 0.10.0

### ISSUE THREAD

**Issue by AdrienPensart** [python-trio/trio-asyncio#52]
Hello,

since update of trio 0.10.0 I have this warning : 

TrioDeprecationWarning: trio.open_cancel_scope is deprecated since Trio 0.10.0; use trio.CancelScope instead (https://github.com/python-trio/trio/issues/607)

Can you fix if it is trivial ?

**Comment by AdrienPensart** [comment]
Will you do a new release soon ?
Cheers.

**Comment by ProvoK** [comment]
Hey there.
I second that, the spam in the logging is quite intense. There is a way to suppress it?

**Comment by pquentin** [comment]
Would one of you be interested in managing trio-asyncio releases?

**Comment by smurfix** [comment]
Yes I know I need to do a new release. Help welcome.

**Comment by ProvoK** [comment]
I don't know your processes but I'm available if I can help.

**Comment by pquentin** [comment]
The process is loosely documented here: https://trio.readthedocs.io/en/latest/releasing.html

There are a number of things you can do even if you can't push to PyPI just yet
