### ISSUE TITLE
release v0.11.0 on PyPI

### ISSUE THREAD

**Issue by schmir-at-bb** [python-trio/trio-asyncio#74]
Version v0.11.0 has been tagged in the git repository, but this version is not available on PyPI at the moment. The latest version on PyPI is v0.10.0.

Are you aware of that? When can we expect the new version?

**Comment by pquentin** [comment]
Hi! Yes, we're aware of that. We're waiting for @smurfix to give PyPI access to @njsmith and @oremanj: https://gitter.im/python-trio/general?at=5e65bf4595b8ff0bbfa2c80c

**Comment by schmir-at-bb** [comment]
ok, thanks.

**Comment by pquentin** [comment]
Thanks @smurfix for adding them! https://pypi.org/project/trio_asyncio/ I guess @oremanj will push the release to PyPI in the next few hours/days now.

**Comment by pquentin** [comment]
0.11.0 is now on PyPI, closing
