### ISSUE TITLE
"You cannot replace an event loop":  multiple parallel / nested loops

### ISSUE THREAD

**Issue by smurfix** [python-trio/trio-asyncio#9]
Multiple loops per Trio run requires contextvars support. That library is new in Python 3.7. There's no backport to 3.6 or 3.5 yet.

**Comment by njsmith** [comment]
You could use `trio.TaskLocal` for now

**Comment by smurfix** [comment]
Actually, I already do. The problem is that for now I need to switch that to a RunLocal, because otherwise subtasks won't see the global event loop.

**Comment by njsmith** [comment]
Wait, why is there a global event loop? :-)

**Comment by smurfix** [comment]
Resolved in f865772 by switching back to a TaskLocal, and monkey-patching asyncio.
